name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.MY_PAT }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.0
            extensions: curl, mbstring, zip, pcntl, iconv
            coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Get Release Notes
        run: ./changelog-checker > ${{ github.workspace }}-CHANGELOG.txt

      - name: Build Binary
        run: php ./changelog-checker app:build ${{github.ref_name}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          name: ${{github.ref_name}}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          generate_release_notes: false
          token: ${{ secrets.MY_PAT }}
          files:
            builds/${{github.ref_name}}
