name: Build Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.MY_PAT }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.0
            extensions: curl, mbstring, zip, pcntl, iconv
            coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Get Release Notes
        run: ./changelog-checker > ${{ github.workspace }}-CHANGELOG.txt

      - name: Build Binary
        run: php ./changelog-checker app:build changelog-checker.phar

      - name: Create GPG signature of PHAR
        run: |
            mkdir -p ~/.gnupg/
            chmod 0700 ~/.gnupg/
            echo "$GPG_SIGNING_KEY" > ~/.gnupg/private.key
            gpg --import ~/.gnupg/private.key
            gpg -u jaymeh@users.noreply.github.com --detach-sign --output builds/changelog-checker.phar.asc builds/changelog-checker.phar
        env:
            GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          name: ${{github.ref_name}}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          generate_release_notes: false
          token: ${{ secrets.MY_PAT }}
          files: |
            builds/changelog-checker.phar
            builds/changelog-checker.phar.asc
